class persona {
    private String tipo;
    private static void main(String[]args);
    private int edad1;
    private void setedad1("27") {           
        this.edad1 = edad1
    
private int getedad1 () {


    private void setnombre("Brie") {
        private int getNombre
    }
}
Private void setTelefono(2200200124)
private int getTelefono 

} ()

}
System.out.println(persona.getNombre());
System.out.println(persona.getedad1());
System.out.println(persona.getTelefono());

Class persona)
int edad;
int nombre;
int telefono;




 Static void main (String[]args) {
    Persona persona = new persona 
    persona.tipo = "ser vivo":;
    System.ou.println(persona.tipo)
}
